//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PdfcrowdDemo {
    
    
    public partial class Default {
        
        protected System.Web.UI.HtmlControls.HtmlForm form1;
        
        protected System.Web.UI.WebControls.TextBox firstName;
        
        protected System.Web.UI.WebControls.TextBox lastName;
        
        protected System.Web.UI.WebControls.DropDownList gender;
        
        protected System.Web.UI.WebControls.CheckBox removeConvertButton;
        
        protected System.Web.UI.HtmlControls.HtmlGenericControl pdfcrowdRemove;
        
        protected System.Web.UI.WebControls.Button asAttachment;
        
        protected System.Web.UI.WebControls.Button asInline;
    }
}
